apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmap.yaml
  - conf-configmap.yaml
  - plugins-configmap.yaml
  - secret.yaml
  - service.yaml
  - headless-service.yaml
  - statefulset.yaml
  - servicemonitor.yaml

labels:
  - includeSelectors: true
    pairs:
      app: rabbitmq
      component: message-broker