apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
data:
  MLFLOW_S3_ENDPOINT_URL: "http://minio-mlflow:9000"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_BACKEND_STORE_URI: "postgresql://mlflow:mlflow123@postgres-mlflow:5432/mlflow"
  MLFLOW_DEFAULT_ARTIFACT_ROOT: "s3://mlflow-artifacts"
  MLFLOW_S3_IGNORE_TLS: "true"
  AWS_EC2_METADATA_DISABLED: "true"