apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  selector:
    matchLabels:
      app: mlflow-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      initContainers:
        # Espera o postgres-mlflow
        - name: wait-for-postgres
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - |
              until nc -z postgres-mlflow 5432; do
                echo "Waiting for PortgreSQL..."
                sleep 2
              done

        # Espera o minio-mlflow
        - name: wait-for-minio
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - |
              until nc -z minio-mlflow 9000; do
                echo "Waiting for MinIO..."
                sleep 2
              done

        # Cria o bucket
        - name: create-bucket
          image: minio/mc:RELEASE.2025-08-13T08-35-41Z
          command:
            - sh
            - -c
            - |
              mc alias set myminio http://minio-mlflow:9000 minio minio123;
              mc mb myminio/mlflow-artifacts || true
          env:
            - name: MC_HOST_myminio
              value: "http://minio:minio123@minio-mlflow:9000"

        - name: install-psycopg2
          image: ghcr.io/mlflow/mlflow:v3.6.0
          command:
            - sh
            - -c
            - |
              pip install --target=/packages cryptography==46.0.3 boto3==1.42.4 psycopg2-binary==2.9.11
          volumeMounts:
            - name: python-packages
              mountPath: /packages

      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v3.6.0
          command:
            - mlflow
            - server
            - --host
            - "0.0.0.0"
            - --port
            - "5000"
            - --backend-store-uri
            - $(MLFLOW_BACKEND_STORE_URI)
            - --default-artifact-root
            - $(MLFLOW_DEFAULT_ARTIFACT_ROOT)
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: MLFLOW_SERVER_ALLOWED_HOSTS
              value: "mlflow-server,mlflow-server:5000,mlflow-server.ml-dev.svc.cluster.local,localhost,localhost:5000,127.0.0.1,127.0.0.1:5000"
            - name: PYTHONPATH
              value: "/packages"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: AWS_SECRET_ACCESS_KEY
          envFrom:
            - configMapRef:
                name: mlflow-config
          volumeMounts:
            - name: python-packages
              mountPath: /packages

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: python-packages
          emptyDir: {}
