apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serving-runtime.yaml
  - inference-service.yaml
  - hpa.yaml
  - service-monitor.yaml

labels:
  - includeSelectors: true
    pairs:
      app: anomaly-detector-predictor
      component: ml-inference
