apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-serve-config
data:
  # MLflow
  MLFLOW_TRACKING_URI: "http://mlflow-server:5000"
  
  # Ray Serve b√°sico
  RAY_SERVE_HTTP_HOST: "0.0.0.0"
  RAY_SERVE_HTTP_PORT: "8000"
  
  # Logging
  RAY_LOGGING_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"