apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-dev

resources:
  - configmap.yaml
  - secret.yaml
  - app-configmap.yaml
  - ray-service.yaml
  - servicemonitor.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      component: inference
      managed-by: kustomize