apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - ray-service.yaml
  - service.yaml
  #- servicemonitor.yaml
  - podmonitor.yaml

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      component: inference
      managed-by: kustomize