apiVersion: v1
kind: Secret
metadata:
  name: ray-serve-secret
type: Opaque
stringData:
  # MinIO/S3 credentials
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-mlflow:9000"