apiVersion: v1
kind: Service
metadata:
  name: ray-metrics
  labels:
    app: ray-cluster
spec:
  selector:
    app: ray-cluster
  ports:
    - name: dashboard
      port: 8265
      targetPort: 8265
    - name: metrics
      port: 8080
      targetPort: 8080
