apiVersion: v1
kind: Service
metadata:
  name: ray-metrics
  labels:
    app: ray-cluster
    component: metrics
spec:
  selector:
    ray.io/cluster: anomaly-detector
    ray.io/node-type: head
  ports:
    - name: dashboard
      port: 8265
      targetPort: 8265
    - name: metrics
      port: 8080
      targetPort: 8080
