apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-mlflow-config
data:
  PGDATA: /var/lib/postgresql/pgdata
  POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
  max_connections: "200"
  shared_buffers: "256MB"
