apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - statefulset.yaml

labels:
  - includeSelectors: true
    pairs:
      app: postgres-mlflow
      component: database
