apiVersion: v1
kind: Service
metadata:
  name: postgres-mlflow
spec:
  clusterIP: None
  selector:
    app: postgres-mlflow
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres-mlflow
