apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-mlflow
spec:
  selector:
    matchLabels:
      app: postgres-mlflow
  serviceName: postgres-mlflow
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-mlflow
    spec:
      containers:
        - name: postgres-mlflow
          image: postgres:18-alpine3.23
          ports:
            - containerPort: 5432
              name: postgres-mlflow
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-mlflow-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-mlflow-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-mlflow-secret
                  key: POSTGRES_DB
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: postgres-mlflow-config
                  key: PGDATA
          volumeMounts:
            - name: postgres-mlflow-data
              mountPath: /var/lib/postgresql/pgdata
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mlflow
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mlflow
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: postgres-mlflow-data
          persistentVolumeClaim:
            claimName: postgres-mlflow-data
