apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - project.yaml
  - app-minikube.yaml

# Labels para identificar recursos do ArgoCD
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/part-of: argocd
