apiVersion: v1
kind: Secret
metadata:
  name: training-worker-secret
type: Opaque
stringData:
  RABBITMQ_URI: "amqp://training:training-service-123@rabbitmq:5672/ml-training"
  
  # MLflow S3/MinIO credentials
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-mlflow:9000"