apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - destination-rule.yaml
  - peer-authentication.yaml
  - request-authentication.yaml
  - authorization-policy.yaml
  - virtual-service.yaml
