apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: anomaly-detector-predictor
  
  jwtRules:
    - issuer: "https://auth.company.com"  # Ajustar para o issuer correto
      jwksUri: "https://auth.company.com/.well-known/jwks.json"
      audiences:
        - "anomaly-detector-api"
      forwardOriginalToken: true
