apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-mlflow
spec:
  selector:
    matchLabels:
      app: minio-mlflow
  replicas: 1
  template:
    metadata:
      labels:
        app: minio-mlflow
    spec:
      containers:
        - name: minio-mlflow
          image: minio/minio:RELEASE.2025-09-07T16-13-09Z
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console

          args:
            - server
            - /data
            - --console-address
            - ":9001"

          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-mlflow-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-mlflow-secret
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_REGION
              valueFrom:
                secretKeyRef:
                  name: minio-mlflow-secret
                  key: MINIO_REGION
            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: minio-mlflow-config
                  key: MINIO_BUCKET_NAME

          volumeMounts:
            - name: minio-mlflow-data
              mountPath: /data

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://127.0.0.1:9000/minio/health/live
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            exec:
              command:
                - curl
                - -f
                - http://127.0.0.1:9000/minio/health/live
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: minio-mlflow-data
          persistentVolumeClaim:
            claimName: minio-mlflow-data
